{"tag": "function", "depth": 1, "time": 1645612026.6445298, "data": {"name": "sleep", "call_args": {"secs": 30.0}, "start_time": 1645611996.6387682, "ret": null, "end_time": 1645612026.6443293}}
{"tag": "function", "depth": 1, "time": 1645612026.6455328, "data": {"name": "assert_equal", "call_args": {"first": "Real opponents", "second": "xyz", "msg": "Checking the text exist"}, "start_time": 1645612026.6445298, "traceback": "Traceback (most recent call last):\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\core\\api.py\", line 709, in assert_equal\n    raise AssertionError(\"%s and %s are not equal, message: %s\" % (first, second, msg))\nAssertionError: Real opponents and xyz are not equal, message: Checking the text exist\n", "end_time": 1645612026.6455328}}
{"tag": "function", "depth": 2, "time": 1645612026.655406, "data": {"name": "try_log_screen", "call_args": {"screen": null, "quality": null, "max_size": null}, "start_time": 1645612026.6455328, "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\RH0539\\Desktop\\AirTestProject\\airtest_poc_MS\\proj_test\\tests\\test_login.py\", line 27, in test_login_valid_credentials\n    assert_equal(\"Real opponents\", \"xyz\", \"Checking the text exist\")\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\core\\api.py\", line 709, in assert_equal\n    raise AssertionError(\"%s and %s are not equal, message: %s\" % (first, second, msg))\nAssertionError: Real opponents and xyz are not equal, message: Checking the text exist\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\core\\cv.py\", line 106, in try_log_screen\n    screen = G.DEVICE.snapshot(quality=quality)\nAttributeError: 'NoneType' object has no attribute 'snapshot'\n", "end_time": 1645612026.655406}}
{"tag": "info", "depth": 0, "time": 1645612026.6455328, "data": {"name": "Assertion error", "traceback": null, "log": "Assertion error"}}
{"tag": "function", "depth": 1, "time": 1645612026.655406, "data": {"name": "assert_equal", "call_args": {"first": "Real opponents", "second": "xyz", "msg": "verify value"}, "start_time": 1645612026.655406, "traceback": "Traceback (most recent call last):\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"c:\\users\\rh0539\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\airtest\\core\\api.py\", line 709, in assert_equal\n    raise AssertionError(\"%s and %s are not equal, message: %s\" % (first, second, msg))\nAssertionError: Real opponents and xyz are not equal, message: verify value\n", "end_time": 1645612026.655406}}
